import 'enum_theme_type.dart';
import 'themes/a11y-dark.dart';
import 'themes/a11y-light.dart';
import 'themes/agate.dart';
import 'themes/an-old-hope.dart';
import 'themes/androidstudio.dart';
import 'themes/arduino-light.dart';
import 'themes/arta.dart';
import 'themes/ascetic.dart';
import 'themes/atelier-cave-dark.dart';
import 'themes/atelier-cave-light.dart';
import 'themes/atelier-estuary-light.dart';
import 'themes/atelier-forest-light.dart';
import 'themes/atelier-heath-light.dart';
import 'themes/atelier-plateau-dark.dart';
import 'themes/atelier-savanna-dark.dart';
import 'themes/atelier-sulphurpool-dark.dart';
import 'themes/atom-one-dark-reasonable.dart';
import 'themes/atom-one-dark.dart';
import 'themes/atom-one-light.dart';
import 'themes/codepen-embed.dart';
import 'themes/color-brewer.dart';
import 'themes/darcula.dart';
import 'themes/dark.dart';
import 'themes/default.dart';
import 'themes/docco.dart';
import 'themes/dracula.dart';
import 'themes/github.dart';
import 'themes/gml.dart';
import 'themes/googlecode.dart';
import 'themes/gradient-dark.dart';
import 'themes/grayscale.dart';
import 'themes/hopscotch.dart';
import 'themes/idea.dart';
import 'themes/ir-black.dart';
import 'themes/lightfair.dart';
import 'themes/magula.dart';
import 'themes/mono-blue.dart';
import 'themes/monokai-sublime.dart';
import 'themes/monokai.dart';
import 'themes/night-owl.dart';
import 'themes/obsidian.dart';
import 'themes/ocean.dart';
import 'themes/paraiso-dark.dart';
import 'themes/pojoaque.dart';
import 'themes/purebasic.dart';
import 'themes/rainbow.dart';
import 'themes/school-book.dart';
import 'themes/solarized-dark.dart';
import 'themes/solarized-light.dart';
import 'themes/tomorrow-night-blue.dart';
import 'themes/tomorrow-night-bright.dart';
import 'themes/tomorrow-night-eighties.dart';
import 'themes/vs.dart';
import 'themes/xcode.dart';

const Map<ThemeType, dynamic> themeMap = {
  ThemeType.a11yDark: a11yDarkTheme,
  ThemeType.a11yLight: a11yLightTheme,
  ThemeType.agate: agateTheme,
  ThemeType.anOldHope: anOldHopeTheme,
  ThemeType.androidstudio: androidstudioTheme,
  ThemeType.arduinoLight: arduinoLightTheme,
  ThemeType.arta: artaTheme,
  ThemeType.ascetic: asceticTheme,
  ThemeType.atelierCaveDark: atelierCaveDarkTheme,
  ThemeType.atelierCaveLight: atelierCaveLightTheme,
  ThemeType.atelierEstuaryLight: atelierEstuaryLightTheme,
  ThemeType.atelierForestLight: atelierForestLightTheme,
  ThemeType.atelierHeathLight: atelierHeathLightTheme,
  ThemeType.atelierPlateauDark: atelierPlateauDarkTheme,
  ThemeType.atelierSavannaDark: atelierSavannaDarkTheme,
  ThemeType.atelierSulphurpoolDark: atelierSulphurpoolDarkTheme,
  ThemeType.atomOneDarkReasonable: atomOneDarkReasonableTheme,
  ThemeType.atomOneDark: atomOneDarkTheme,
  ThemeType.atomOneLight: atomOneLightTheme,
  ThemeType.codepenEmbed: codepenEmbedTheme,
  ThemeType.colorBrewer: colorBrewerTheme,
  ThemeType.darcula: darculaTheme,
  ThemeType.dark: darkTheme,
  ThemeType.defaultTheme: defaultTheme,
  ThemeType.docco: doccoTheme,
  ThemeType.dracula: draculaTheme,
  ThemeType.github: githubTheme,
  ThemeType.gml: gmlTheme,
  ThemeType.googlecode: googlecodeTheme,
  ThemeType.gradientDark: gradientDarkTheme,
  ThemeType.grayscale: grayscaleTheme,
  ThemeType.hopscotch: hopscotchTheme,
  ThemeType.idea: ideaTheme,
  ThemeType.irBlack: irBlackTheme,
  ThemeType.lightfair: lightfairTheme,
  ThemeType.magula: magulaTheme,
  ThemeType.monoBlue: monoBlueTheme,
  ThemeType.monokaiSublime: monokaiSublimeTheme,
  ThemeType.monokai: monokaiTheme,
  ThemeType.nightOwl: nightOwlTheme,
  ThemeType.obsidian: obsidianTheme,
  ThemeType.ocean: oceanTheme,
  ThemeType.paraisoDark: paraisoDarkTheme,
  ThemeType.pojoaque: pojoaqueTheme,
  ThemeType.purebasic: purebasicTheme,
  ThemeType.rainbow: rainbowTheme,
  ThemeType.schoolBook: schoolBookTheme,
  ThemeType.solarizedDark: solarizedDarkTheme,
  ThemeType.solarizedLight: solarizedLightTheme,
  ThemeType.tomorrowNightBlue: tomorrowNightBlueTheme,
  ThemeType.tomorrowNightBright: tomorrowNightBrightTheme,
  ThemeType.tomorrowNightEighties: tomorrowNightEightiesTheme,
  ThemeType.vs: vsTheme,
  ThemeType.xcode: xcodeTheme
};
